export const CHANGE_SEARCH = 'CHANGE_SEARCH';
export const RETRIEVE_MOVIES = 'RETRIEVE_MOVIES';
export const ADD_NOMINATION = 'ADD_NOMINATION';
export const REMOVE_NOMINATION = 'REMOVE_NOMINATION';
export const CLOSE_BANNER = 'CLOSE_BANNER';